# Content API Contract for AI-Robot Brain Module

openapi: 3.0.0
info:
  title: AI-Robot Brain Educational Content API
  description: API for accessing educational content related to NVIDIA Isaac Sim, Isaac ROS, and Nav2 for humanoid robotics
  version: 1.0.0

paths:
  /content/chapters:
    get:
      summary: Get all available chapters
      description: Retrieve a list of all chapters in the AI-Robot Brain module
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'

  /content/chapters/{chapterId}:
    get:
      summary: Get specific chapter content
      description: Retrieve content for a specific chapter by ID
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
          description: ID of the chapter to retrieve
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found

  /content/examples:
    get:
      summary: Get available examples
      description: Retrieve a list of all implementation examples in the AI-Robot Brain module
      responses:
        '200':
          description: List of examples
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Example'

  /content/examples/{exampleId}:
    get:
      summary: Get specific example
      description: Retrieve details for a specific implementation example by ID
      parameters:
        - name: exampleId
          in: path
          required: true
          schema:
            type: string
          description: ID of the example to retrieve
      responses:
        '200':
          description: Example details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        '404':
          description: Example not found

  /content/validation:
    post:
      summary: Validate AI-robot configuration
      description: Validate an AI-robot configuration against best practices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIConfiguration'
      responses:
        '200':
          description: Validation results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'

components:
  schemas:
    Chapter:
      type: object
      required:
        - id
        - title
        - content
        - order
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Title of the chapter
        content:
          type: string
          description: Markdown content of the chapter
        order:
          type: integer
          description: Order of the chapter in the module
        description:
          type: string
          description: Brief description of the chapter
        objectives:
          type: array
          items:
            type: string
          description: Learning objectives for the chapter

    Example:
      type: object
      required:
        - id
        - title
        - description
        - technology
      properties:
        id:
          type: string
          description: Unique identifier for the example
        title:
          type: string
          description: Title of the example
        description:
          type: string
          description: Detailed description of the example
        technology:
          type: string
          enum: [isaac-sim, isaac-ros, nav2]
          description: Primary technology focus of the example
        files:
          type: array
          items:
            type: string
          description: List of files included in the example
        prerequisites:
          type: array
          items:
            type: string
          description: Prerequisites needed to run the example
        steps:
          type: array
          items:
            type: string
          description: Step-by-step instructions for the example

    AIConfiguration:
      type: object
      required:
        - simulation_config
        - perception_pipeline
        - navigation_config
      properties:
        simulation_config:
          type: string
          description: Isaac Sim configuration
        perception_pipeline:
          type: string
          description: Isaac ROS perception pipeline configuration
        navigation_config:
          type: string
          description: Nav2 navigation configuration
        robot_model:
          type: string
          description: Robot URDF or model description
        hardware_requirements:
          type: object
          description: Hardware requirements for the configuration
          properties:
            gpu:
              type: string
              description: Required GPU type
            memory:
              type: integer
              description: Required memory in GB

    ValidationResult:
      type: object
      required:
        - valid
        - issues
      properties:
        valid:
          type: boolean
          description: Whether the configuration is valid
        issues:
          type: array
          items:
            $ref: '#/components/schemas/ValidationIssue'
        recommendations:
          type: array
          items:
            type: string
          description: Recommendations for improvement

    ValidationIssue:
      type: object
      required:
        - severity
        - message
      properties:
        severity:
          type: string
          enum: [error, warning, info]
          description: Severity level of the issue
        message:
          type: string
          description: Description of the issue
        location:
          type: string
          description: Location where the issue occurs