import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the AI Native Book
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ROS 2 for Humanoid Robotics',
      items: [
        'ros2-nervous-system/introduction-to-ros2',
        'ros2-nervous-system/ros2-communication',
        'ros2-nervous-system/urdf-robot-structure',
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin/physics-simulation-gazebo',
        'digital-twin/digital-twins-unity',
        'digital-twin/sensor-simulation-validation',
      ],
    },
    {
      type: 'category',
      label: 'AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'ai-robot-brain/nvidia-isaac-sim',
        'ai-robot-brain/isaac-ros-vslam',
        'ai-robot-brain/nav2-path-planning',
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA)',
      items: [
        'vla/voice-to-action-whisper',
        'vla/cognitive-planning-llms',
        'vla/capstone-autonomous-humanoid',
      ],
    },
    // Add more categories as needed
  ],
};

export default sidebars;
